name: flutterfinalproject
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0  # Un-comment this to use Firebase
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  get: ^4.6.6
  percent_indicator: ^4.2.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
