// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtp5naGjW4EgxywkDhZeL9jLtREKxaby8',
    appId: '1:415638620059:web:086f01042263268298433e',
    messagingSenderId: '415638620059',
    projectId: 'task-management-app-8afc3',
    authDomain: 'task-management-app-8afc3.firebaseapp.com',
    storageBucket: 'task-management-app-8afc3.appspot.com',
    measurementId: 'G-Z8TB9V5YR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGj70itcsz6JJcggHseyZy228X0w8_8I',
    appId: '1:415638620059:android:0b2029494d473d5798433e',
    messagingSenderId: '415638620059',
    projectId: 'task-management-app-8afc3',
    storageBucket: 'task-management-app-8afc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXf5MY6YZCgaP1Xo2VgFWbk5DRDufT89w',
    appId: '1:415638620059:ios:610ca025d5d8ea1598433e',
    messagingSenderId: '415638620059',
    projectId: 'task-management-app-8afc3',
    storageBucket: 'task-management-app-8afc3.appspot.com',
    iosClientId: '415638620059-qitpocimk4r83iv8qb55kg0g51njmdv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXf5MY6YZCgaP1Xo2VgFWbk5DRDufT89w',
    appId: '1:415638620059:ios:610ca025d5d8ea1598433e',
    messagingSenderId: '415638620059',
    projectId: 'task-management-app-8afc3',
    storageBucket: 'task-management-app-8afc3.appspot.com',
    iosClientId: '415638620059-qitpocimk4r83iv8qb55kg0g51njmdv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtp5naGjW4EgxywkDhZeL9jLtREKxaby8',
    appId: '1:415638620059:web:c5ea904cba355e5998433e',
    messagingSenderId: '415638620059',
    projectId: 'task-management-app-8afc3',
    authDomain: 'task-management-app-8afc3.firebaseapp.com',
    storageBucket: 'task-management-app-8afc3.appspot.com',
    measurementId: 'G-S5X16643GQ',
  );
}
